 zookeeper:
   container_name: zookeeper
   restart: always
   image: zookeeper:3.4.11
   ports:
      - "2181:2181"

 kafka:
   container_name: kafka
   image: wurstmeister/kafka
   restart: always
   links:
       - zookeeper:zk
   ports:
       - "9092:9092"
   environment:
       KAFKA_ADVERTISED_HOST_NAME: localhost
       KAFKA_ADVERTISED_PORT: "9092"
       KAFKA_ZOOKEEPER_CONNECT: zk:2181

 mysql:
  image: mysql:5.6.23
  ports:
    - "33061:3306"
  environment:
     TZ : "Asia/Shanghai"
     MYSQL_ROOT_PASSWORD: 123456
     MYSQL_DATABASE: db_transaction
  command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:4.0
    ports:
      - "6379:6379"
